<?php
use Illuminate\Database\Migrations\Migration;use Illuminate\Database\Schema\Blueprint;use Illuminate\Support\Facades\Schema;
return new class extends Migration{private function audit(Blueprint $t,bool $soft=true):void{$t->foreignId('created_by')->nullable()->constrained('users');$t->foreignId('updated_by')->nullable()->constrained('users');$t->timestamps();if($soft)$t->softDeletes();}
public function up():void{Schema::create('course_activities',function(Blueprint $t){$t->id();$t->string('type',20);$t->string('code',60)->unique();$t->string('name');$t->string('slug');$t->decimal('official_academic_hours',8,2);$t->json('base_syllabus_json')->nullable();$t->decimal('reference_price',14,2)->nullable();$t->boolean('talk_includes_certificate')->default(false);$t->decimal('talk_certificate_price',14,2)->default(0);$t->boolean('is_active')->default(true);$t->index(['type','is_active']);$t->index('name');$this->audit($t);});
Schema::create('course_editions',function(Blueprint $t){$t->id();$t->foreignId('course_activity_id')->constrained('course_activities');$t->string('code',60)->nullable()->unique();$t->string('state',30)->default('draft');$t->string('modality',30);$t->date('starts_on')->nullable();$t->date('ends_on')->nullable();$t->string('address')->nullable();$t->string('access_url')->nullable();$t->decimal('price_amount',14,2)->default(0);$t->char('currency',3)->default('PEN');$t->json('syllabus_override_json')->nullable();$t->foreignId('responsible_user_id')->nullable()->constrained('users');$t->unsignedSmallInteger('delivery_due_days')->default(1);$t->timestamp('validations_completed_at')->nullable();$t->index(['course_activity_id','state']);$t->index(['responsible_user_id','state']);$t->index(['starts_on','ends_on']);$this->audit($t);});
Schema::create('course_edition_teachers',function(Blueprint $t){$t->foreignId('course_edition_id')->constrained('course_editions')->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained('users');$t->string('display_name');$t->string('email')->nullable();$t->unsignedSmallInteger('sort_order')->default(1);$t->primary(['course_edition_id','sort_order']);});
Schema::create('course_sessions',function(Blueprint $t){$t->id();$t->foreignId('course_edition_id')->constrained('course_editions');$t->date('session_date')->nullable();$t->time('starts_at')->nullable();$t->time('ends_at')->nullable();$t->string('teacher_name')->nullable();$t->string('topic');$t->unsignedSmallInteger('sort_order')->default(1);$t->unique(['course_edition_id','sort_order']);$this->audit($t);});
Schema::create('course_participants',function(Blueprint $t){$t->id();$t->foreignId('customer_id')->nullable()->constrained('customers');$t->foreignId('contact_id')->nullable()->constrained('contacts');$t->string('first_name');$t->string('last_name');$t->string('document_type')->nullable();$t->string('document_number')->nullable();$t->string('email')->nullable();$t->string('mobile')->nullable();$t->string('document_number_norm')->nullable();$t->string('email_norm')->nullable();$t->string('mobile_norm')->nullable();$t->unique(['document_type','document_number_norm'], 'course_participants_document_unique');$this->audit($t);});
Schema::create('course_enrollment_groups',function(Blueprint $t){$t->id();$t->foreignId('course_edition_id')->constrained('course_editions');$t->foreignId('payer_customer_id')->nullable()->constrained('customers');$t->string('payer_name');$t->string('payer_document_type')->nullable();$t->string('payer_document_number')->nullable();$t->text('notes')->nullable();$this->audit($t);});
Schema::create('course_enrollments',function(Blueprint $t){$t->id();$t->foreignId('course_edition_id')->constrained('course_editions');$t->foreignId('course_participant_id')->constrained('course_participants');$t->foreignId('course_enrollment_group_id')->nullable()->constrained('course_enrollment_groups');$t->string('state',30)->default('enrolled');$t->string('payment_status',30)->default('pending');$t->decimal('activity_price_amount',14,2)->default(0);$t->decimal('certificate_charge_amount',14,2)->default(0);$t->decimal('discount_amount',14,2)->default(0);$t->decimal('subtotal_amount',14,2)->default(0);$t->char('currency',3)->default('PEN');$t->timestamp('participation_confirmed_at')->nullable();$t->decimal('exact_average',8,4)->nullable();$t->decimal('display_average',8,2)->nullable();$t->unsignedTinyInteger('rounded_result')->nullable();$t->string('final_result',30)->default('pending');$t->timestamp('result_calculated_at')->nullable();$t->unique(['course_edition_id','course_participant_id'], 'course_enrollments_edition_participant_unique');$this->audit($t);});
Schema::create('course_attendances',function(Blueprint $t){$t->id();$t->foreignId('course_session_id')->constrained('course_sessions');$t->foreignId('course_enrollment_id')->constrained('course_enrollments');$t->string('status',20)->default('unmarked');$t->foreignId('marked_by')->nullable()->constrained('users');$t->timestamp('marked_at')->nullable();$t->timestamps();$t->unique(['course_session_id','course_enrollment_id'], 'course_attendances_session_enrollment_unique');});
Schema::create('course_grades',function(Blueprint $t){$t->id();$t->foreignId('course_session_id')->constrained('course_sessions');$t->foreignId('course_enrollment_id')->constrained('course_enrollments');$t->string('description')->nullable();$t->decimal('grade',4,2);$t->foreignId('entered_by')->nullable()->constrained('users');$t->timestamp('entered_at')->nullable();$t->unique(['course_session_id','course_enrollment_id']);$this->audit($t);});
Schema::create('course_certificate_templates',function(Blueprint $t){$t->id();$t->string('name');$t->string('type_scope')->nullable();$t->unsignedInteger('version')->default(1);$t->boolean('is_active')->default(true);$t->string('blade_view')->nullable();$t->longText('html_template')->nullable();$t->json('settings_json')->nullable();$this->audit($t);});
Schema::create('course_academic_documents',function(Blueprint $t){$t->id();$t->foreignId('course_enrollment_id')->constrained('course_enrollments');$t->foreignId('course_certificate_template_id')->nullable()->constrained('course_certificate_templates');$t->foreignId('document_id')->nullable()->constrained('documents');$t->string('type',40);$t->string('status',40)->default('pending_generation');$t->string('code')->unique();$t->date('issue_date')->nullable();$t->string('filename')->nullable();$t->string('qr_token_hash')->nullable();$t->timestamp('qr_token_revoked_at')->nullable();$t->timestamp('qr_token_last_used_at')->nullable();$t->foreignId('replaced_by_id')->nullable()->constrained('course_academic_documents');$t->timestamp('annulled_at')->nullable();$t->foreignId('annulled_by')->nullable()->constrained('users');$t->text('annul_reason')->nullable();$t->timestamp('last_sent_at')->nullable();$t->string('delivery_status',30)->default('pending');$t->text('delivery_discard_reason')->nullable();$this->audit($t);});
Schema::create('course_commercial_documents',function(Blueprint $t){$t->id();$t->foreignId('course_enrollment_group_id')->nullable()->constrained('course_enrollment_groups');$t->foreignId('course_enrollment_id')->nullable()->constrained('course_enrollments');$t->foreignId('document_id')->nullable()->constrained('documents');$t->string('type',20);$t->string('series')->nullable();$t->string('number')->nullable();$t->date('issue_date')->nullable();$t->char('currency',3)->default('PEN');$t->decimal('subtotal_amount',14,2);$t->decimal('igv_rate',5,4)->default(.18);$t->decimal('igv_amount',14,2);$t->decimal('total_amount',14,2);$t->string('payer_name');$t->string('payer_document_type')->nullable();$t->string('payer_document_number')->nullable();$t->text('observations')->nullable();$t->string('status',30)->default('pending_file');$t->timestamp('last_sent_at')->nullable();$this->audit($t);});}
public function down():void{foreach(['course_commercial_documents','course_academic_documents','course_certificate_templates','course_grades','course_attendances','course_enrollments','course_enrollment_groups','course_participants','course_sessions','course_edition_teachers','course_editions','course_activities'] as $t)Schema::dropIfExists($t);}};
