@extends('layouts.app')
@section('title', 'Dashboard de soporte')
@section('page-title', 'Dashboard de soporte')
@section('content')
    <form method="GET" class="card card-body mb-3"><div class="row g-2">
        <div class="col-md-2"><label class="form-label">Desde</label><input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="form-control"></div><div class="col-md-2"><label class="form-label">Hasta</label><input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="form-control"></div>
        @foreach (['customer_id'=>'Cliente','responsible_id'=>'Responsable','team_id'=>'Equipo','type_id'=>'Tipo','category_id'=>'Categoría','priority_id'=>'Prioridad','status_id'=>'Estado'] as $field => $label)
            @php($items = ['customer_id' => $customers, 'responsible_id' => $users, 'team_id' => $teams, 'type_id' => $types, 'category_id' => $categories, 'priority_id' => $priorities, 'status_id' => $statuses][$field])
            <div class="col-md-2"><label class="form-label">{{ $label }}</label><select name="{{ $field }}" class="form-select"><option value="">Todos</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(($filters[$field] ?? '') == $item->id)>{{ $item->name ?? $item->code }}</option>@endforeach</select></div>
        @endforeach
        <div class="col-md-2"><label class="form-label">Modalidad</label><select name="modality" class="form-select"><option value="">Todas</option>@foreach(['virtual'=>'Virtual','presential'=>'Presencial','phone'=>'Teléfono','not_applicable'=>'No aplica'] as $value=>$label)<option value="{{ $value }}" @selected(($filters['modality'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
        <div class="col-12"><button class="btn btn-primary">Filtrar</button><a class="btn btn-outline-secondary" href="{{ route('support.dashboard') }}">Limpiar</a><a class="btn btn-outline-success" href="{{ route('support.export', request()->query()) }}">Exportar CSV</a></div>
    </div></form>
    <div class="row g-3"><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Tickets recibidos</div><div class="h3 mb-0">{{ $metrics['total'] }}</div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Prom. primera respuesta</div><div class="h5 mb-0">{{ number_format($metrics['average_first_response_seconds'] / 3600, 2) }} h</div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Prom. resolución</div><div class="h5 mb-0">{{ number_format($metrics['average_resolution_seconds'] / 3600, 2) }} h</div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="text-muted small">Reabiertos</div><div class="h5 mb-0">{{ number_format($metrics['reopened_percent'], 2) }}%</div></div></div></div></div>
    <div class="row g-3 mt-1">@foreach(['by_state'=>'Por estado','by_priority'=>'Por prioridad','observations'=>'Observaciones'] as $key=>$title)<div class="col-lg-4"><div class="card"><div class="card-header"><h2 class="h6 mb-0">{{ $title }}</h2></div><div class="card-body p-0"><table class="table mb-0"><tbody>@forelse($metrics[$key] as $label=>$count)<tr><td>{{ $label }}</td><td class="text-end">{{ $count }}</td></tr>@empty<tr><td class="text-muted">Sin datos</td></tr>@endforelse</tbody></table></div></div></div>@endforeach</div>
@endsection
